[[main]]
none = "none"

[[main]]
name = "Publications"
pageRef = "publications"
identifier = "oqpe0DhLQi"
weight = 9_999

[[main]]
name = "Talks"
pageRef = "talks"
identifier = "iWi0uGIYCS"
weight = 9_999

[[footer]]
none = "none"
